version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t "$DOCKER_USERNAME"/localizeos:latest .
            docker tag "$DOCKER_USERNAME"/localizeos:latest "$DOCKER_USERNAME"/localizeos:$CIRCLE_RUN_NUMBER
      - run:
          name: Push Docker image
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push "$DOCKER_USERNAME"/localizeos:latest
            docker push "$DOCKER_USERNAME"/localizeos:$CIRCLE_RUN_NUMBER

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: stage
